name: Lint
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run linting
        run: npm lint
